### ISSUE TITLE
Fields missing from workflow tab for certificate nodes only

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#10]
Restore functionality 

field_certificate_term, field_certificate_class, and field_certificate_classname, and the node body fields previously displayed in the workflow tab for certificate nodes only.

**Comment by knieper** [comment]
I need more information on this. 

Looking at my local copy of the site as of 10-6-15 I see the node title, it's current state, and then workflow history (with columns of date, old state, new state, by, comment). See screenshot.

![screen shot 2016-01-11 at 6 05 31 pm](https://cloud.githubusercontent.com/assets/812430/12249529/51a45d60-b88e-11e5-9567-fe725a170ce0.png)

Was this functionality something that existed before October? Where and how did those fields display?

**Comment by jynxiesue** [comment]
Here are screen shots of a C1 certificate View and Workflow.  The afore mentioned fields that show up in View do not show up in Workflow, but used to. 
![certificate_view](https://cloud.githubusercontent.com/assets/16547623/12270570/b8ec6954-b924-11e5-9d5e-40f65768f33d.jpg)
![certificate_workflow](https://cloud.githubusercontent.com/assets/16547623/12270574/bc4407ec-b924-11e5-882d-75ac8af5ee23.jpg)

**Comment by crlt** [comment]
there are instructions that should also appear in the workflow view. those instructions are set here: 
http://crlt.umich.edu/crlt/certificate/workflow-instructions

**Comment by mbakewel** [comment]
Just as an update, we noticed that this is looking like it's working, but did not have time to rigorously test it today. We'll get to it in our next testing meeting.

**Comment by mbakewel** [comment]
Tested - all good.
