### ISSUE TITLE
"Download Signup Sheet" on the event nodes does not export attendance data.

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#12]
Seminar titles with Commas in them yield a "Duplicate Headers received from the server" error when attempting to download signup lists; fix is to remove commas from Seminar titles before downloading  or use a browser other than Chrome.  Could we rewrite the download script to strip commas?

**Comment by knieper** [comment]
notes for later - The download function is manually created by the custom module crlt signup. It relies on the view 'BM_signup_status_user_vbo_admin' to provide the data to the download function. Likely an issue with it's manual handling of the fields.

**Comment by mbakewel** [comment]
works!
