### ISSUE TITLE
WYSIWYG editor error - trouble changing URL on CRLT website - just noting in case repeated

### ISSUE THREAD

**Issue by anjirlly** [knieper/crltmich#13]
MORE EXAMPLES TO BE ADDED IF PROBLEM RE-OCCURS

Pam finally changed URL in code; neither she nor Ryan could update a teaching strategies webpage
http://www.crlt.umich.edu/tstrategies/tsd
in the "as you see it" window in Chrome or Firefox (even after re-starting). At the final step of the process accessed thru the link icon; after editing what the viewer sees, copying in the new URL, and setting the target to "new window_blank," the OK button turned yellow, and we couldn't finish the change.

**Comment by knieper** [comment]
Unable to reproduce. I am able to make edits (adding new links, adding '_blank' as a target, removing links) to this page and to other pages. Tested in both Firefox and Chrome. 

Please test again and let me know if you continue to see the problem.

**Comment by anjirlly** [comment]
Will do, Sharon. Thanks for the follow up.

Ryan/anjirlly
