### ISSUE TITLE
Adding a field for players Internal vs External performance to content_type_events

### ISSUE THREAD

**Issue by amyhamermesh** [knieper/crltmich#15]
Can Meg just add this, or do we need to give it more thought?

**Comment by knieper** [comment]
Amy - I'll add this to the list for when I speak to Meg next week.

**Comment by amyhamermesh** [comment]
that was exactly Meg's goal when she had me create it...

_Did you know you can get immediate computer support by_
_Calling 4-Help -- 734-764-HELP (4357)_\* or *_chatting the helpdesk
at https://chatsupport.it.umich.edu https://chatsupport.it.umich.edu_
_You can also get help with less time-sensitive issues by sending an email
to 4help@umich.edu 4help@umich.edu_

Amy

~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~
Amy Beth Hamermesh, Desktop Support
ITS Shared Services MiWorkspace • Neighborhood IT
0170i Health Service  • and • 1071 Palmer Drive Commons
Phone: (734) 763-4176 • and • (734)936-2596
amybeth@umich.edu       •       http://its.umich.edu/help/
~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~

**Comment by knieper** [comment]
It doesn't look like this happened...should I implement?

**Comment by amyhamermesh** [comment]
I think so, yes? Meg?

Amy

~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~
Amy Beth Hamermesh, Desktop Support
ITS Shared Services MiWorkspace • Neighborhood IT
0170i Health Service  • and • 1071 Palmer Drive Commons
Phone: (734) 763-4176 • and • (734)936-2596  
amybeth@umich.edu       •       http://its.umich.edu/help/
~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~_~

On Thu, May 12, 2016 at 2:31 PM -0700, "Sharon Knieper" notifications@github.com wrote:

It doesn't look like this happened...should I implement?

**Comment by amyhamermesh** [comment]
Yes, please.

**Comment by knieper** [comment]
Field has been added.
