### ISSUE TITLE
new consultation node created from old webform submission

### ISSUE THREAD

**Issue by crlt** [knieper/crltmich#20]
A client submitted webform response on node 468 on 2-oct-15. At this time, as expected, a consultation node was created (nid 86647). Unexpectedly, a second consultation node (89377) was created on 14-Jan-16 based on the same web request. Only one consultation node should be created per webform submission. As far as I know, this is the only instance of this unexpected behavior happening. (Raised by Erping to Meg on 15-Jan-16.)

**Comment by knieper** [comment]
Looking farther into this the second consultation node (89377) actually links to a different submission (http://crlt.umich.edu/node/468/submission/13184) than the first consultation node. *_This submission does not have a consultation node. *_ It as if when the #13184 submission was sent through the content (the user and their request description) was carried over from the previous submission to the consultation node.

I've tried to recreate this behavior on the development site and on my local copy - and have not been able to reproduce it.

I've looked into the date/time of this submission and it was submitted at a time when the code updates were being pushed in mid December. I suspect there was some interaction there that caused this. If we see it again I'll look more into it but I believe this was a one time bug.
