### ISSUE TITLE
Change status of (some?) Tyler-made C2s to approved

### ISSUE THREAD

**Issue by anjirlly** [knieper/crltmich#24]
Meg 2/25/16:
These were created by Tyler from completed services on our database that are eligible for certificates, that existed before we had the automatic creation system. For example, now, when an MSF is completed, it is supposed to make a C2 node automatically (much like the way a TP consult is supposed to make an E certificate node automatically. To handle the fact that this process was not occurring when we were on sitemaker, Tyler created a whole bunch of certificates based on consults that were in our database. I've looked at some examples, and it appears to have worked well for the most part, although I do see that some of the created certs are in the "new needs review" status instead of the "Approved" status they should be in. So, rather than clearing these out, I think we need to make sure they have the right status. They can be identified as nodes created by tjfrank, certificate type = c2, source = consultation, source id corresponds to a valid consultation node. They should all be approved status. You can add this to github issues.

Meg 12/10/15:
These might be some part of the import of data from Sitemaker. I want to see where they come from before purging.

Ryan 12/10/15:
In reviewing C2s in the dashboard view, almost all of them look like the result of testing by tjfrank, created 7/28/14. Is it possible to clear these out?

http://crlt.umich.edu/crlt/certificate/overview?field_certificate_type_value_many_to_one_op=or&field_certificate_type_value_many_to_one%5B%5D=C2&sid_op=in&sid%5B%5D=6&uid=

**Comment by knieper** [comment]
Per conversation with Meg it looks like this was resolved already
