### ISSUE TITLE
2 fields not working in grant report reminder email

### ISSUE THREAD

**Issue by mbakewel** [knieper/crltmich#26]
In the reminder email that goes out to grant recipients to remind the of a report due soon or overdue, two fields (grant title and report due date) are not merging into the email that goes out. See example below. Missing fields are indicated with *****.

---

Dear Colleague,
In 2015, you received funding from the Lecturers' Professional Development Fund for the project titled: [field_grant_application_title]*****

Grantee(s): Susan Crabb

Our records indicate that your project has concluded. CRLT requires grantees to submit final reports no later than 3 months after a project’s conclusion. Please remember to submit your final grant report by *****, using CRLT's Kerberos Password protected report website: https://crlt.umich.edu/mygrants

Once you have logged in and selected the appropriate project, you will be asked to recap the goals of your project; detail the achievements of the project (including the number of students and/or courses affected by the project); discuss any plans for continuation and dissemination of the project; and provide advice to your U-M colleagues considering similar work.

All reports will be published on CRLT's website to assist your U-M faculty colleagues in improving teaching and learning across campus: http://crlt.umich.edu/viewgrantreports.

If you have any questions, please e-mail us (crltgrants@umich.edu). We hope your project has been successful, and we look forward to receiving your report.

Best regards,

Center for Research on Learning and Teaching (CRLT)

**Comment by knieper** [comment]
As noted in #34 the title token should be fixed, but I've not seen any problems with the report due field in any of my testing. 

Many of the applications do not have a report due value, so theoretically could go through blank, but I was never able to get the email to trigger without that field filled in.

**Comment by mbakewel** [comment]
Can we use project end date + 90 instead of report due date? Or somehow
automatically edit report due date to be end date + 90 on node add/edit?

On Mon, Apr 4, 2016 at 11:40 PM, Sharon Knieper notifications@github.com
wrote:

> As noted in #34 https://github.com/knieper/crltmich/issues/34 the title
> token should be fixed, but I've not seen any problems with the report due
> field in any of my testing.
> 
> Many of the applications do not have a report due value, so theoretically
> could go through blank, but I was never able to get the email to trigger
> without that field filled in.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/knieper/crltmich/issues/26#issuecomment-205627687

## 

---

Meg Bakewell, Ph.D.
Assistant Director
Center for Research on Learning and Teaching (CRLT)

**Comment by mbakewel** [comment]
Hi Sharon, 

Can you please prioritize this, top of the list? Deb would like an ETA. She got an email from grant recipient who got a report reminder (with missing due date) even though he already submitted his report. I think we have talked about how the workflow status should advance to Report Complete when the report is submitted, but in this case (on prod, so not unexpectedly) the status was not updated when the report was submitted. Deb has since updated the status. 

We also need an email to go to the user who updated the node with the report, confirming that their report was received. I tried doing this on prod with a rule - http://crlt.umich.edu/admin/rules/rules/rules_confirmation_that_report_was_received

and it seems to sort of maybe work - but the email that goes out has those weird A characters - I will forward that to you separately so you can see. I deactivated the rule for now since the email formatting is not working. 

Here a link to the grant application Deb emailed me about: http://crlt.umich.edu/node/86533/workflow

Here's the email: - note that the formatting is not good in this - no line breaks. 

On Jun 3, 2016, at 1:25 PM, crltgrants@umich.edu wrote:

Dear Colleague, In 2015, you received funding from the Lecturers' Professional Development Fund for the project titled: Humanize the Numbers Grantee(s): Isaac Wingfield [1] Our records indicate that your project has concluded. CRLT requires grantees to submit final reports no later than 3 months after a project’s conclusion. Please remember to submit your final grant report by , using CRLT's Kerberos Password protected report website: https://crlt.umich.edu/mygrants Once you have logged in and selected the appropriate project, you will be asked to recap the goals of your project; detail the achievements of the project (including the number of students and/or courses affected by the project); discuss any plans for continuation and dissemination of the project; and provide advice to your U-M colleagues considering similar work. All reports will be published on CRLT's website to assist your U-M faculty colleagues in improving teaching and learning across campus: http://crlt.umich.edu/viewgrantreports. If you have any questions, please e-mail us (crltgrants@umich.edu). We hope your project has been successful, and we look forward to receiving your report. Best regards, Center for Research on Learning and Teaching (CRLT) [1] http://crlt.umich.edu/users/iwing

**Comment by knieper** [comment]
Nodeapi adjustment was made so that on initial save of grant application nodes the report due field is automatically filled in based off of the project end date. It also will update exisiting nodes that are missing a report due field but will not alter those that already have dates set.

This is staged but is in the same branch as the feature on certificates that allows for updating of profile fields so is not yet in production.

**Comment by knieper** [comment]
Project end date is being filled in automatically and reworked the view that handles notifications to use the report due date field instead of the project 'end date'. This would allow for backlog processing if ever required in the future.
