### ISSUE TITLE
apostrophe problem in some emails generated when even node created

### ISSUE THREAD

**Issue by anjirlly** [knieper/crltmich#27]
When creating a new event node, an apostrophe in the title field turns into &#039; in the subject line of the email notice that I receive about the node's creation. (See screencap below.) Neither the confirmation email nor a broadcast email sent to registrants have this problem.
![screen shot 2016-03-07 at 4 38 13 pm](https://cloud.githubusercontent.com/assets/16194827/13584403/8168163c-e484-11e5-80a6-5abc6fcb4dc0.png)

**Comment by knieper** [comment]
Looks like this was an issue with the tokens in the rule set. Changing from subject token from using [node:title] to [node:title-raw] it works fine. Since the users creating events are trusted internal users this should be fine.
