### ISSUE TITLE
Grant application field field_grant_application_grad_stu: error when user does not exist

### ISSUE THREAD

**Issue by mbakewel** [knieper/crltmich#28]
The field field_grant_application_grad_stu appears in the grant application form (aka grant application node add: http://crlt.umich.edu/node/add/grant-application). It's a userref field, so when an username that does not exist in our website is entered, it gives an error on save. It's possible that there was a typo in the username (unqiname) so it's good to flag this for the user, but if they confirm that it is the real uniqname, then they have no recourse other than to email us. We need either better messaging about what the user should do, e.g. email crltgrants@umich.edu, or probably preferable, a way to override the error after warning the user/asking "are you sure?". Maybe just add the user. 

The same is true for other userref field on grants, but it is more likely to cause an error with grad students because, compared to faculty, fewer of them are in our database of users.

**Comment by knieper** [comment]
The content from field_grant_application_grad_stu was only filled in on 11 nodes. It was transferred manually to a new simple text field 'field_grant_app_grad_stu_2' and permissions on the old field removed. 

The plan is to create custom process in the backend to silently create a new account for faculty uniqnames not found in the database and email staff when an account is created. If there is a spelling error and staff are unable to determine the real uniqname the applicant can be contacted.

**Comment by knieper** [comment]
Silent creation of accounts is happening. Mail notification to staff needs work yet.

**Comment by knieper** [comment]
email notification of new account creation to 'crltwebteam' email is working correctly.

**Comment by knieper** [comment]
Changed email notification to go to crltgrants@umich.edu and added account creation for applicants not yet in the database as well as faculty.
