### ISSUE TITLE
certificate emails to verifiers coming from wrong email address

### ISSUE THREAD

**Issue by mbakewel** [knieper/crltmich#31]
Emails from the system should come from "UMGraduateTeacherCertificate@umich.edu" but it appears that at least some of them (e.g., C2 to verifier) are coming from UMGraduateTeacherCertficate@umich.edu (certificate is missing an i)

**Comment by mbakewel** [comment]
I am not sure if we can test this while all emails are going to you. How can we modify that setting during our testing?

**Comment by knieper** [comment]
Just saw this...unfortunately setting the 'test' email is set in code....I've pushed a change to dev.crlt.umich.edu so that emails are sent to you for now.

**Comment by mbakewel** [comment]
Thanks.

On Saturday, April 2, 2016, Sharon Knieper notifications@github.com wrote:

> Just saw this...unfortunately setting the 'test' email is set in
> code....I've pushed a change to dev.crlt.umich.edu so that emails are
> sent to you for now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/knieper/crltmich/issues/31#issuecomment-204831515

## 

---

Meg Bakewell, Ph.D.
Assistant Director
Center for Research on Learning and Teaching (CRLT)

**Comment by jynxiesue** [comment]
Emails are coming from the correct address: UMGraduateTeacherCertificate@umich.edu.
