### ISSUE TITLE
signups eligible for B certificates

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#32]
There are 3 types of B certificates.  On this page:
http://www.crlt.umich.edu/um.gtc/focal_area_b_resources_and_support 
and in the printable document:
http://www.crlt.umich.edu/sites/default/files/certificaterequirements_20140401.pdf
The information is consistent.  Screen shots follow.
![screen shot 2016-03-21 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/16547623/13928274/5f254e18-ef6b-11e5-835a-f09acc58ee67.png)
![screen shot 2016-03-21 at 1 47 00 pm](https://cloud.githubusercontent.com/assets/16547623/13928301/70aa03e0-ef6b-11e5-9a20-c909f37f8cbd.png)

When a user submits a B certificate, they are allowed to submit only B1 and B2 certificates, but on their certificate page, B1 and B2 are reversed from the above. These need to be changed. The
Screen shot of the user's page and submission forms for both B1 and B2 follow.
![screen shot 2016-03-21 at 1 45 01 pm](https://cloud.githubusercontent.com/assets/16547623/13928366/bcfd47d4-ef6b-11e5-8e3e-4890947c3fe9.png)
![screen shot 2016-03-21 at 2 06 15 pm](https://cloud.githubusercontent.com/assets/16547623/13928921/1fa68f92-ef6e-11e5-8392-0525fd8e5882.png)
![screen shot 2016-03-21 at 2 06 38 pm](https://cloud.githubusercontent.com/assets/16547623/13928937/2a4b04dc-ef6e-11e5-9b70-90da0072c30b.png)

**Comment by knieper** [comment]
Staging site should be set to create B1 and B2 certs according to the original printable document.

Events coded as eligible for B2's will create B2s and for events coded as eligible for B3 current create B2's.

**Comment by knieper** [comment]
Pushed to production

**Comment by knieper** [comment]
Changed events coded to be eligible for B3's to B1's per Meg on 8-24-16.
Tests on dev node 92776 show proper certificate creation.
Pushed to production.
