### ISSUE TITLE
Grants: Workflow should change to "Report Complete" when report is submitted

### ISSUE THREAD

**Issue by mbakewel** [knieper/crltmich#33]
When 
- the grant application node is edited (likely by the node owner, an authorized user, but possibly by CRLT Staff), AND 
- the current workflow state is any of (Funded, Report Due, Report Overdue) AND 
- any of the report fields listed below are changed

Then 
- the workflow state should be set to "Report Complete" AND 
- an email indicating that the report as received should be sent to crltgrants@umich.edu.  

Email template: 
Subject line: Grant Report Received - [Grant title] - [applicant last name]
Body: link to node.

Report fields: 
field_grant_app_proj_objectives
field_grant_app_proj_achievement
field_grant_app_continuation
field_grant_app_dissemination
field_grant_app_colleague_advice
field_grant_app_crlt_advice

**Comment by knieper** [comment]
I've set a series of rules/actions that appear to solve this issue on the staging site and it is ready for testing.

Caveat: The applicant's last name is not an available token, however the username, typically the uniqname, is available so that is what is passed in the subject line

**Comment by mbakewel** [comment]
also need to be sure email goes to person who submitted the report to confirm report was rec'd

**Comment by lgonza** [comment]
Submitted reports in dev, but workflow did not change to "report complete". I didn't receive an email confirmation, and crltgrants did not receive an email that a report had been submitted.

**Comment by knieper** [comment]
Should be working correctly in production now - included two rules: 
Grants: Set Workflow when report is complete
and 
Grants: Send confirmation emails when report is complete
