### ISSUE TITLE
Grants: check report reminder email process and handle backlog

### ISSUE THREAD

**Issue by mbakewel** [knieper/crltmich#34]
For grant applications with workflow state in (Funded, Report Due, Report Overdue), three reminder emails about the report due date should be sent via cron to the first applicant. 
- When the end date is less than 30 days from now, send first reminder and set field_grant_app_reminders_sent = 1.
- When the end date is 30 days ago, send second reminder, set field_grant_app_reminders_sent = 2, and set workflow status to Report Due. 
- When the end date is 75 days ago, send third reminder, field_grant_app_reminders_sent = 3, and set workflow status to Report Overdue. 
- If somehow the first or second reminder did not get sent on time, but it is now time to send a subsequent reminder, do not send 2 and then 3 (for example) on the same day - just skip to the latest applicable reminder.
- No further reminders are sent after the third. 

The view http://crlt.umich.edu/admin/build/views/edit/grant_report_reminder_01 is involved with sending grant report reminders - it identifies the nodes that need reminders, and according to our testing prior to grants launch, it was doing that just fine. However, there were some problems with cron (it would not consistently send emails on time) and there were some problems with the email text (see issue #26 ), so many of the records that were imported from the previous system (Sitemaker) were imported with a null value in field_grant_app_suppress_request which prevents report reminder emails from going out at all. Since it has now been some months since deployment, many of these suppressed applications have reached or passed their end dates and never received their report reminders. We would like to send one reminder email to them outside of Drupal, and set their status to report due/overdue/etc, so that they can re-enter the normal reminder process if applicable. 

I believe that new grant_applications created in Drupal post-launch are getting reminder emails, but I am not certain if it is working correctly or consistently. for transparency, it would be useful to cc: crltgrants@umich.edu on all of the reminder emails. Email reminder settings are configured here: http://crlt.umich.edu/admin/crlt/grant-applications/report-mail-settings

**Comment by knieper** [comment]
From testing it looks like an application will not trigger emails unless the field 'Report due' is filled in. Is this part of the staff reviewing process? 

Once that field is filled in emails are sent based on the project dates. I've been able to force testing of the emails by editing these fields. 

Regarding issue #26: The title field in the emails was a problem with the wrong token being used - that is now fixed. I've never been able to mimic a situation where the date field is not filled in. For my testing the email will not send if the report due date field is empty.

I'll see if I can set the emails to cc crltgrants and about a plan to handle the grants that had emails suppressed but before going too far down that line I'd like to confirm that the Report Due field is something that consistently gets filled in by staff.

**Comment by knieper** [comment]
The staging site is set to send a copy of the email to crltgrants - but with an adjusted subject line so that you know it's just a copy of what was sent to the user.

**Comment by mbakewel** [comment]
Report due date is supposed to be calculated as the project end date + 90
days. I am not sure why this field was included, given that everything else
seems to be based off of the project end date.

On Mon, Apr 4, 2016 at 6:13 PM, Sharon Knieper notifications@github.com
wrote:

> From testing it looks like an application will not trigger emails unless
> the field 'Report due' is filled in. Is this part of the staff reviewing
> process?
> 
> Once that field is filled in emails are sent based on the project dates.
> I've been able to force testing of the emails by editing these fields.
> 
> Regarding issue #26 https://github.com/knieper/crltmich/issues/26: The
> title field in the emails was a problem with the wrong token being used -
> that is now fixed. I've never been able to mimic a situation where the date
> field is not filled in. For my testing the email will not send if the
> report due date field is empty.
> 
> I'll see if I can set the emails to cc crltgrants and about a plan to
> handle the grants that had emails suppressed but before going too far down
> that line I'd like to confirm that the Report Due field is something that
> consistently gets filled in by staff.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/knieper/crltmich/issues/34#issuecomment-205518669

## 

---

Meg Bakewell, Ph.D.
Assistant Director
Center for Research on Learning and Teaching (CRLT)

**Comment by knieper** [comment]
I've adjusted the view in staging to use the report due field now that it will be reliably filled in. 
- The first notice goes out 120 days before the report is due - which is one month before the project ends.
- The second notice goes out 60 days before the report is due - which is one month after the project has finished.
- The third notice goes out the day the report is due - which is 3 months after the project is finished.

By using the report due field previously suppressed grants can have new report due dates filled in and then start the normal process without skipping notices. It should not affect behavior for new grants as the report due field will be calculated off the project end date.

While this should occur automatically on cron, you may wish to have staff make it part of their existing Monday routine to click the 'Send report reminders' button on the CRLT Grant Report Mail Settings page just to make sure things happen regularly.

**Comment by knieper** [comment]
New view was pushed to production.

Per Meg - pre-existing grant applications were manually emailed about their report status, so I did not yet go through and update older grant applications regarding their missing report due fields. This should probably be done at some point.
