### ISSUE TITLE
Graduate Teacher Certificate:formatting of automated verification request emails

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#35]
Automated emails are going out to verifiers but they are not formatted correctly.  All lines are run together with odd characters interspersed. Screen shot is attached.
![screen shot 2016-05-24 at 1 43 40 pm](https://cloud.githubusercontent.com/assets/16547623/15514133/98cb8f66-21b5-11e6-83b3-dfd8c3e9f1e2.png)

**Comment by knieper** [comment]
Email formatting should be resolved.

**Comment by jynxiesue** [comment]
Thank you so much!
