### ISSUE TITLE
Urgent: Grants: grant application permissions for anon/auth should be workflow status dependent

### ISSUE THREAD

**Issue by mbakewel** [knieper/crltmich#38]
I accidentally discovered a problem with the grant application content type visibility/permissions. It is set up so that a grant application is visible to anon/auth users, which is fine and in fact necessary if and only if the grant workflow status is funded, report complete, report due, or report overdue. 

Example node: http://crlt.umich.edu/node/86175 - workflow = not funded, but was visible as anonymous user. For the moment, I took permission away to see grant applications for anyone except CRLT staff, but this will need to be addressed ASAP because our public facing grant reports view (http://crlt.umich.edu/viewgrantreports) is otherwise empty. 

This moves straight to the top of the list. Please advise how this can best be addressed as soon as you can.

**Comment by knieper** [comment]
Solved by new rule set that publishes/unpublishes nodes depending on workflow status.
