### ISSUE TITLE
Certificate: certificates nodes (type=E) are not being created when consultation node is updated

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#40]
Ii've have had a number of emails saying participants E certificates, teaching philosophies, have been approved but they are not showing up in the portfolios.  I emailed the first occurrence asking that they make sure the the node is updated as follows:
Status = Complete 
Is it for certificate? = Yes 
Teaching philosophy approved = Yes (or No if not) 
The GTC wrote back with the following screen shot:
![screen shot 2016-08-08 at 3 22 36 pm](https://cloud.githubusercontent.com/assets/16547623/17492913/06a68ab6-5d7c-11e6-851a-57ff3f03619c.png)

**Comment by mbakewel** [comment]
1. when a consultation node (meeting 5 requirements: 1) type = teaching philosophy, 2) status = complete, 3) for certificate = yes, and 4) teaching philosophy approved = yes, author of the node has profile value = 'Graduate Student' for the Role/Rank field) is updated, a certificate node with certificate type = E should be created and workflow should be set to approved. The update to the consultation node is typically done by a user with the GTC role. Problem: the certificate node is not being created when GTCs update consultation nodes. However, if uid 10 (rhudson) with role CRLT Staff saves the consultation record, the certificate node is created.
