### ISSUE TITLE
Verifiers are not able to view and set workflow state on the certificate nodes for C1, C2, and D

### ISSUE THREAD

**Issue by jynxiesue** [knieper/crltmich#7]
If current logged in user has the umich uniqname corresponding to "field_certificate_mail " (including @umich.ed and/or @med.umich.edu), AND the workflow state is "Needs Verification", that user should be able to change the workflow state to "Needs Review" (seen by user as "I Agree" - this code exists) or "Denied" (seen by user at "I Disagree" - this code exists). 
Code is at sites/all/modules/custom/crlt/modules/crlt_certificate/crlt_certificate.module

**Comment by jynxiesue** [comment]
The above functionality used to work but got broken sometime over the summer possibly when grants was deployed.

**Comment by mbakewel** [comment]
The user can now set the workflow, but the "I agree" and "I disagree" are not showing up. These should be the only two options available - other options like approved, etc. are also available to the user.

**Comment by anjirlly** [comment]
![screen shot 2016-03-22 at 4 03 48 pm](https://cloud.githubusercontent.com/assets/16194827/13966439/d2984b6a-f048-11e5-801f-7f7399b00dca.png)

**Comment by knieper** [comment]
This may be showing if the logged in user has additional permissions (like CRLT staff).

If I am a 'verifer' I see the agree/disagree only (see screenshot) but still have 'needs work' showing. I'll revise to remove 'needs work'
![screen shot 2016-03-24 at 2 25 22 pm](https://cloud.githubusercontent.com/assets/812430/14027135/8d98f728-f1cc-11e5-8e9f-46d0e008fa4b.png)

**Comment by knieper** [comment]
Now shows just I agree/disagree...example node is 89391 when logged in 'sharonknieper@umich.edu' which is currently set to be the verifier.
![screen shot 2016-03-24 at 2 34 06 pm](https://cloud.githubusercontent.com/assets/812430/14027356/97bb525e-f1cd-11e5-9bd2-5701484db2a0.png)

**Comment by mbakewel** [comment]
tested - all good.
