### ISSUE TITLE
certificate type E nodes created without workflow state

### ISSUE THREAD

**Issue by anjirlly** [knieper/crltmich#9]
Restoring lost functionality

When a consultation node  is updated AND consultation type = teaching philosophy AND approved for certificate = yes AND submitted for certificate = yes, AND no duplicate certificates exist, then a certificate node type = E is created. It should be created with the workflow = approved, but it has been created with no workflow state. 

field names
field_consult_type
field_consultation_tp_approved
field_consultation_tp_cert

**Comment by crlt** [comment]
we may also see the certificate node not being created at all. One instance observed with node 88860. When this node was set to complete/approved/submitted for certificate, it didn't make a certificate node (or we can;t find the node it made).

**Comment by knieper** [comment]
This appears to be a problem with workflow permissions. I added the ability for GTC users to move certs from creation to approved and denied and then from denied to approved.  

However, it looks like currently the code does not allow for E certificates to be moved back to denied from approved by editing the consultation node. Basically once they are approved the only way to change the certificate status is from the certificate itself - not the consultation. This seems reasonable but I want to make sure it is the desired behavior.

**Comment by knieper** [comment]
There was a certificate for node 88860 made - it was node 89347.

**Comment by crlt** [comment]
There is no need to move it to denied from approved. Once approved, it's
done. If someone approves by mistake, they would report to supervisor for a
CRLT staff member to fix that. (I think all CRLT staff have sufficient
workflow privileges to address this - if not, at least Jeri and I do.) To
be clear, GTCs do no ever go to the workflow tab and edit the state
directly - it all should happen in code when tey update the consultation
node.

On Sun, Mar 13, 2016 at 4:38 PM, Sharon Knieper notifications@github.com
wrote:

> There was a certificate for node 88860 made - it was node 89347.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knieper/crltmich/issues/9#issuecomment-196048074.

## 

---

Meg Bakewell, Ph.D.
Assistant Director
Center for Research on Learning and Teaching (CRLT)

**Comment by knieper** [comment]
Great! Thanks for clarifying

**Comment by mbakewel** [comment]
The E certificate node is created with the workflow state "New Request - Needs Review" instead of "Approved"

**Comment by mbakewel** [comment]
still creating certificate node with status = new request" - but status should be approved. 
![image](https://cloud.githubusercontent.com/assets/5739661/14212781/80fb728e-f802-11e5-93ae-d8964352f5dc.png)
![image](https://cloud.githubusercontent.com/assets/5739661/14212784/86d1c370-f802-11e5-99f5-c90b681f0df9.png)

**Comment by knieper** [comment]
It looks like it was related to workflow permissions. At the moment the workflow transition is recorded the user that needs to have the workflow permission is the service provider. Since we don't want service providers to necessarily have permission to do this to all certificates I set the permission bypass in code. Should be ready for testing again.

**Comment by jynxiesue** [comment]
No E certificates showing up when I filter for them with workflow state as "No State".  New teaching philosophies are showing up as "Approved" E certificates in students' portfolios.
